### PR TITLE
Fix bold/italic on canvas

### PR DESCRIPTION
**Pull request by anuj9196**
I tested it and working with me.
Added bold/italic to canvas font.

### CODE REVIEW

**Comment by vincent7128** [comment]
Can you add your test in the github page?

**Comment by anuj9196** [comment]
Sorry, @vincent7128 can't add it. I can share screenshots if you say.

**Comment by vincent7128** [comment]
Why not? Any problems?

**Comment by anuj9196** [comment]
Check demo here: https://anuj9196.github.io/text-image/demo/

**Comment by anuj9196** [comment]
Please make sure to update file paths in index.html and demo.js files as I have updated them to work in my code.

**Pull request merged**
